#!/bin/bash
#SBATCH --job-name="OD-magma-test-01"
#SBATCH --output="OD-magma-test-01.%j.%N.out"
#SBATCH --partition=gpu-shared
#SBATCH --gres=gpu:2
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --export=ALL
#SBATCH -t 00:10:00

#This job runs with 1 node with 2 cores, and 1 GPU
#ibrun in verbose mode will give binding detail

ibrun -v ./driverAM workflowAM.cfg
